name: ArtifactTest
version: ${project.version}
main: me.tmanti.artifacttest.ArtifactTest
api-version: 1.13
commands:
  add:
    description: "adds to attribute"
    usage: "/add [amount]"
  addscalar:
    description: "scalar add"
    usage: "/scalar [amount]"
  multiplyscalar:
    description: "scalar multiplication"
    usage: "/multiplyscalar [amount]"
  getTest:
    description: "test stick"
    usage: "/getTest [amount]"